name: Rust

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install linux libs
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config build-essential gcc-multilib libudev-dev libgtk-3-dev

      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D clippy::all
      - name: test
        run: cargo test

  build_and_release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [check]
    name: Build and Release
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: fontpad_linux.tar.gz
          - target: x86_64-apple-darwin
            os: macOS-latest
            name: fontpad_mac.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: fontpad_windows.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install linux deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config build-essential gcc-multilib libudev-dev libgtk-3-dev

      - name: build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare build artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip fontpad.exe
          7z a ../../../${{ matrix.name }} fontpad.exe
          cd -
      - name: Prepare build artifacts [-nix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip fontpad
          tar cvf ../../../${{ matrix.name }} fontpad
          cd -
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}